#!/bin/bash

ip_address=$(cat /home/kali/.config/panels/target | awk '{print $1}')
machine_name=$(cat /home/kali/.config/panels/target | awk '{print $2}')
 
if [ $ip_address ] && [ $machine_name ]; then
    echo " $ip_address - $machine_name    "
else
    echo "# No target    "
fi
